server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: Mkx6d1@667
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
pixabay:
  api: https://api.pexels.com/v1/search?query=
  key: r7Dcbc9pPanI7UmwxvMngcFNLqX0XgECNQJa95ybJD2qmzHm8Ldrh3my